# Generated by Django 5.2.17 on 2026-08-28 02:19

import django.db.models.deletion
import properties.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('purpose', models.CharField(choices=[('sale', 'Venda'), ('rent', 'Locação')], max_length=8, verbose_name='finalidade')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('penthouse', 'Cobertura'), ('land', 'Terreno'), ('office', 'Sala comercial'), ('store', 'Loja'), ('building', 'Prédio')], max_length=16, verbose_name='tipo de imóvel')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('rented', 'Alugado'), ('archived', 'Arquivado')], default='draft', max_length=12, verbose_name='situação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='preço')),
                ('show_price', models.BooleanField(default=True, verbose_name='exibir preço')),
                ('condominium_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='condomínio')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='área total')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='quartos')),
                ('suites', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='suítes')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='banheiros')),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='vagas de garagem')),
                ('street', models.CharField(max_length=180, verbose_name='logradouro')),
                ('number', models.CharField(max_length=30, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='bairro')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(default='RJ', max_length=2, verbose_name='estado')),
                ('postal_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('address_visibility', models.CharField(choices=[('full', 'Endereço completo'), ('neighborhood_city', 'Bairro e cidade')], default='neighborhood_city', max_length=20, verbose_name='exibição do endereço')),
                ('exact_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude exata')),
                ('exact_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude exata')),
                ('public_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude aproximada')),
                ('public_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude aproximada')),
                ('map_visibility', models.CharField(choices=[('hidden', 'Mapa oculto'), ('approximate', 'Localização aproximada')], default='hidden', max_length=12, verbose_name='exibição do mapa')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('featured_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='ordem do destaque')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado à lixeira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['-is_featured', 'featured_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=180, verbose_name='título do imóvel')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('status_changed', 'Situação alterada'), ('trashed', 'Enviado à lixeira'), ('restored', 'Restaurado'), ('deleted', 'Excluído definitivamente')], max_length=20, verbose_name='ação')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='alterações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='realizada em')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_changes', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='properties.property', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'alteração do imóvel',
                'verbose_name_plural': 'alterações dos imóveis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.property_image_path, verbose_name='imagem')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='texto alternativo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_cover', models.BooleanField(default=False, verbose_name='foto principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='imóvel')),
            ],
            options={
                'verbose_name': 'imagem do imóvel',
                'verbose_name_plural': 'imagens dos imóveis',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'deleted_at'], name='properties__status_fb6018_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose', 'property_type'], name='properties__purpose_4ca319_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood'], name='properties__city_27bef8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', 'featured_order'], name='properties__is_feat_59d1fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='property_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('condominium_fee__isnull', True), ('condominium_fee__gte', 0), _connector='OR'), name='property_condominium_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('total_area__gt', 0)), name='property_total_area_positive'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(fields=('property', 'order'), name='unique_property_image_order'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('property',), name='unique_property_cover_image'),
        ),
    ]
