# Generated by Django 5.2.17 on 2026-08-28 03:00

import properties.models
import properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='tamanho do arquivo'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='altura'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_format',
            field=models.CharField(blank=True, editable=False, max_length=12, verbose_name='formato'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='largura'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_image_path, validators=[properties.validators.validate_property_image], verbose_name='imagem'),
        ),
    ]
