import logoChindler from '../logo_chindler_peq_nova.png';
import iconLocacao from '../Locacao_imoveis.png';
import iconCondominios from '../Administracao_condominios.png';
import iconCompraVenda from '../Compra_Venda_imoveis.png';

const services = [
  ['Locação de Imóveis', 'A Chindler coloca à sua disposição serviços com o objetivo de proporcionar tranquilidade, através de ferramentas que transmitam segurança e transparência.', iconLocacao],
  ['Administração de Condomínios', 'A Chindler possui uma cobrança única de taxa de administração. Ao contrário de todo o mercado, cobramos apenas o valor da taxa, sem nenhum outro tipo de cobrança extra.', iconCondominios],
  ['Compra e Venda de Imóveis', 'A Chindler trabalha no sistema de exclusividade. Com isso, o seu imóvel não será anunciado por diversas empresas e corretores, de formas e preços diferentes.', iconCompraVenda],
];

export default function Home() {
  return (
    <main>
      <header className="nav"><a className="brand" href="#inicio" aria-label="Chindler, início"><img className="brand-logo" src={logoChindler.src} alt="Chindler" /></a><nav aria-label="Navegação principal"><a href="https://chindler.com.br/aluguel" target="_blank" rel="noreferrer">Balcão de Imóveis</a><a href="https://chindler.com.br/servicos" target="_blank" rel="noreferrer">Condomínio</a><a href="#contato">Contato</a></nav><a className="nav-cta" href="https://admin107486.superlogica.net/clients/areadocondomino" target="_blank" rel="noreferrer">Portal do Cliente</a></header>
      <section className="hero" id="inicio"><img className="hero-image" src="/guanabara-sunset.jpg" alt="Pôr do sol sobre a Baía de Guanabara, no Rio de Janeiro" /><div className="hero-shade" /><div className="hero-content"><p className="eyebrow">ADMINISTRADORA DE IMÓVEIS • RIO DE JANEIRO</p><h1>Seu patrimônio<br /><em>em boas mãos.</em></h1><p className="hero-copy">Desde 1976, a Chindler administra imóveis e condomínios com experiência, transparência e atendimento direto pelos diretores.</p><a className="button light" href="#atuacao">Conheça nossos serviços <span>→</span></a></div><div className="scroll-note">ROLE PARA DESCOBRIR <span>↓</span></div></section>
      <section className="intro" id="sobre"><p className="section-label">01 — QUEM SOMOS</p><div><h2>Desde 1976, confiança que atravessa <em>gerações.</em></h2><p>Fundada por José Chindler, a Chindler é uma empresa familiar e referência no mercado imobiliário do Rio de Janeiro. Com sede própria na Avenida Rio Branco e mais de 5.000 clientes, oferece assessoria administrativa e jurídica especializada em locação, compra e venda de imóveis e administração de condomínios. Seu grande diferencial é o atendimento verdadeiramente personalizado: os clientes são acompanhados diretamente pelos diretores, com proximidade, segurança e qualidade em cada etapa.</p><a className="text-link" href="#contato">Fale com a Chindler ↗</a></div></section>
      <section className="services" id="atuacao"><div className="services-head"><p className="section-label">02 — ÁREAS DE ATUAÇÃO</p><h2>Serviços <em>Chindler</em></h2></div><div className="service-list">{services.map(([title,copy,icon])=><article key={title as string}><img className="service-icon" src={icon.src} alt="" aria-hidden="true" /><h3>{title}</h3><p>{copy}</p><a href="#contato" aria-label={`Saiba mais sobre ${title}`}>↗</a></article>)}</div></section>
      <section className="statement" id="juridico"><p className="statement-label">ASSESSORIA ESPECIALIZADA</p><h2>Departamento <em>Jurídico</em></h2><p className="statement-copy">A Chindler tem origem no Escritório de Advocacia José Chindler e reúne décadas de experiência no setor imobiliário. Seu departamento jurídico conta com advogados especializados em diferentes áreas, oferecendo suporte ágil, orientações claras e soluções objetivas para as questões do dia a dia. Assim, os clientes tomam decisões com mais segurança, tranquilidade e acompanhamento permanente.</p></section>
      <section className="numbers" id="numeros" aria-label="Números da Chindler"><div><strong>50</strong><span>anos de experiência</span></div><div><strong>5.000+</strong><span>clientes atendidos</span></div></section>
      <section className="contact" id="contato"><div className="contact-info"><p className="section-label">03 — CONTATO E LOCALIZAÇÃO</p><h2>Fale com a <em>Chindler.</em></h2><div className="contact-map"><iframe title="Localização da Chindler na Avenida Rio Branco, Rio de Janeiro" src="https://www.google.com/maps?q=Av.%20Rio%20Branco%2C%20109%20-%20Centro%2C%20Rio%20de%20Janeiro%20-%20RJ&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></div><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=Av.%20Rio%20Branco%2C%20109%2C%20Centro%2C%20Rio%20de%20Janeiro%2C%20RJ" target="_blank" rel="noreferrer">Abrir no Google Maps ↗</a></div><form><label>Nome<input type="text" placeholder="Seu nome" /></label><label>E-mail<input type="email" placeholder="voce@empresa.com" /></label><label>Como podemos ajudar?<textarea rows={3} placeholder="Conte-nos brevemente sobre sua necessidade" /></label><button type="submit">Enviar mensagem <span>→</span></button></form></section>
      <footer><div className="brand"><img className="brand-logo footer-logo" src={logoChindler.src} alt="Chindler" /></div><p>Av. Rio Branco, 109 - 18º Andar<br />Centro - Rio de Janeiro - RJ</p><p>© 2026 Chindler</p></footer>
    </main>
  );
}
