'use client';
import { useMemo, useState } from 'react';
import logoChindler from '../../logo_chindler_peq_nova.png';
import { imoveis } from './imoveis';
const dinheiro = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});

export default function ImoveisPage(){
  const [finalidade,setFinalidade]=useState('Todos'); const [tipo,setTipo]=useState('Todos'); const [bairro,setBairro]=useState('Todos'); const [busca,setBusca]=useState('');
  const resultado=useMemo(()=>imoveis.filter(i=>(finalidade==='Todos'||i.finalidade===finalidade)&&(tipo==='Todos'||i.tipo===tipo)&&(bairro==='Todos'||i.bairro===bairro)&&`${i.titulo} ${i.bairro}`.toLowerCase().includes(busca.toLowerCase())),[finalidade,tipo,bairro,busca]);
  const limpar=()=>{setFinalidade('Todos');setTipo('Todos');setBairro('Todos');setBusca('')};
  return <main className="property-page">
    <header className="nav"><a className="brand" href="/" aria-label="Chindler, início"><img className="brand-logo" src={logoChindler.src} alt="Chindler" /></a><nav aria-label="Navegação principal"><a href="/imoveis">Balcão de Imóveis</a><div className="nav-dropdown"><button type="button" aria-haspopup="true">Condomínio <span aria-hidden="true">⌄</span></button><div className="dropdown-menu"><a href="/condominio/servicos">Serviços</a><a href="/condominio/diferenciais">Diferenciais da Chindler</a><a href="/condominio/taxa-administrativa">Taxa Administrativa</a></div></div><a href="/#contato">Contato</a></nav><a className="nav-cta" href="https://admin107486.superlogica.net/clients/areadocondomino" target="_blank" rel="noreferrer">Portal do Cliente</a></header>
    <section className="property-hero"><div><p className="eyebrow">BALCÃO DE IMÓVEIS • RIO DE JANEIRO</p><h1>Encontre o lugar certo para <em>o seu momento.</em></h1><p>Imóveis selecionados para comprar ou alugar, com atendimento próximo e segurança em todas as etapas.</p></div></section>
    <section className="property-search" aria-label="Busca de imóveis"><div className="purpose-tabs">{['Todos','Comprar','Alugar'].map(item=><button key={item} className={finalidade===item?'active':''} onClick={()=>setFinalidade(item)}>{item}</button>)}</div><div className="filter-row"><label>BUSCAR<input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Bairro ou palavra-chave" /></label><label>TIPO<select value={tipo} onChange={e=>setTipo(e.target.value)}><option>Todos</option><option>Apartamento</option><option>Casa</option><option>Comercial</option></select></label><label>BAIRRO<select value={bairro} onChange={e=>setBairro(e.target.value)}><option>Todos</option>{[...new Set(imoveis.map(i=>i.bairro))].map(item=><option key={item}>{item}</option>)}</select></label><div className="filter-count"><strong>{resultado.length}</strong><span>imóveis encontrados</span></div></div></section>
    <section className="property-results"><div className="results-head"><div><p className="section-label">IMÓVEIS SELECIONADOS</p><h2>Comprar ou alugar com <em>tranquilidade.</em></h2></div><p>A Chindler acompanha você da busca à assinatura do contrato.</p></div>{resultado.length?<div className="property-grid">{resultado.map(i=><article className="property-card" key={i.id}><div className="property-photo"><img src={i.imagem} alt={i.titulo}/>{i.destaque&&<span className="featured">Destaque</span>}<span className="purpose">{i.finalidade}</span></div><div className="property-card-body"><p className="property-location">{i.tipo} • {i.bairro}</p><h3>{i.titulo}</h3><div className="property-features">{i.quartos>0&&<span>{i.quartos} quartos</span>}<span>{i.banheiros} banheiros</span><span>{i.area} m²</span></div><div className="property-price"><div><strong>{dinheiro.format(i.preco)}</strong>{i.finalidade==='Alugar'&&<span>/mês</span>}</div><a href={`mailto:contato@chindler.com.br?subject=Interesse no imóvel ${i.id}`} aria-label={`Tenho interesse em ${i.titulo}`}>→</a></div></div></article>)}</div>:<div className="empty-results"><h3>Nenhum imóvel encontrado.</h3><p>Tente remover algum filtro ou buscar por outro bairro.</p><button onClick={limpar}>Limpar filtros</button></div>}</section>
    <section className="inner-cta"><p className="section-label">ATENDIMENTO CHINDLER</p><h2>Não encontrou o imóvel ideal?</h2><p className="property-cta-copy">Conte o que você procura e nossa equipe ajuda a encontrar as melhores opções.</p><a className="button light" href="/#contato">Fale com a Chindler <span>→</span></a></section>
    <footer><div className="brand"><img className="brand-logo footer-logo" src={logoChindler.src} alt="Chindler" /></div><div className="footer-details"><p>Av. Rio Branco, 109 - 18º Andar<br/>Centro - Rio de Janeiro - RJ</p><a className="footer-contact" href="tel:+552122216453"><span aria-hidden="true">☎</span> (21) 2221-6453</a></div><p>© 2026 Chindler</p></footer>
  </main>;
}
