# Generated by Django 5.2.17 on 2026-08-28 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=180, verbose_name='título do imóvel')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_progress', 'Em atendimento'), ('visit_scheduled', 'Visita agendada'), ('completed', 'Concluído'), ('discarded', 'Descartado')], default='new', max_length=20, verbose_name='situação')),
                ('consent_version', models.CharField(max_length=30, verbose_name='versão do consentimento')),
                ('consent_at', models.DateTimeField(verbose_name='consentimento registrado em')),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True, verbose_name='último atendimento em')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='anonimizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property', verbose_name='imóvel')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'interessado',
                'verbose_name_plural': 'interessados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='leads_lead_status_2b0e1e_idx'), models.Index(fields=['responsible', 'status'], name='leads_lead_respons_aa9700_idx'), models.Index(fields=['last_interaction_at'], name='leads_lead_last_in_c3cc19_idx')],
            },
        ),
    ]
