# Generated by Django 5.2.17 on 2026-08-29 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('properties', '0002_propertyimage_file_size_propertyimage_height_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Observação'), ('call', 'Ligação'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('visit', 'Visita'), ('status_change', 'Alteração de situação'), ('assignment', 'Alteração de responsável'), ('task_completed', 'Tarefa concluída')], default='note', max_length=20, verbose_name='tipo')),
                ('description', models.TextField(verbose_name='descrição')),
                ('outcome', models.CharField(blank=True, max_length=180, verbose_name='resultado')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'histórico de atendimento',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('call', 'Ligação'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('visit', 'Visita'), ('follow_up', 'Retorno'), ('other', 'Outro')], max_length=15, verbose_name='tipo')),
                ('due_at', models.DateTimeField(verbose_name='data e horário')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='observação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='pending', max_length=10, verbose_name='situação')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'próxima ação',
                'verbose_name_plural': 'próximas ações',
                'ordering': ['due_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluído em'),
        ),
        migrations.AddField(
            model_name='lead',
            name='discard_reason',
            field=models.TextField(blank=True, verbose_name='motivo do descarte'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='prioridade'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Site'), ('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('referral', 'Indicação'), ('manual', 'Cadastro manual')], default='website', max_length=15, verbose_name='origem'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority', 'created_at'], name='leads_lead_priorit_0d0c1b_idx'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead', verbose_name='interessado'),
        ),
        migrations.AddField(
            model_name='leadtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_tasks', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
        migrations.AddField(
            model_name='leadtask',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead', verbose_name='interessado'),
        ),
        migrations.AddField(
            model_name='leadtask',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['lead', '-occurred_at'], name='leads_leadi_lead_id_00dfcf_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtask',
            index=models.Index(fields=['status', 'due_at'], name='leads_leadt_status_912851_idx'),
        ),
        migrations.AddIndex(
            model_name='leadtask',
            index=models.Index(fields=['responsible', 'status', 'due_at'], name='leads_leadt_respons_526fc3_idx'),
        ),
    ]
