# Generated by Django 5.2.17 on 2026-08-29 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadinteraction_leadtask_lead_completed_at_and_more'),
        ('properties', '0002_propertyimage_file_size_propertyimage_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='consentimento registrado em'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='consent_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='versão do consentimento'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property', verbose_name='imóvel'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='título do imóvel'),
        ),
    ]
